name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.15.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --reporter=verbose
        timeout-minutes: 10

      - name: Setup Git User
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Build marketing-site
        run: pnpm nx build marketing-site

      - name: Deploy to GitHub Pages
        run: pnpm nx deploy marketing-site
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENV: ${{ github.event.inputs.environment || github.ref_name }}
